# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
  
  repository_dispatch:
    types:
      - webhook
  schedule:
    - cron: "0 */1 * * 0"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: |
          node scraping/leaderboard.js
          git config user.name kings-league-bot
          git diff --quiet && git diff --staged --quiet || git commit -am "[bot] update Kings League database"
          git push origin master
